server {
    listen 80;
    server_name localhost;

    location /kanban-test-project/ {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /kanban-test-project/index.html;
    }

    location /kanban-test-project/mockServiceWorker.js {
        root /usr/share/nginx/html;
        add_header Service-Worker-Allowed '/kanban-test-project/';
    }

    # proxy API calls to the api service (internal docker network hostname)
    location /api/ {
        proxy_pass http://api:5000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}