server {
  listen 80;
  server_name localhost;
  
  location /kanban-test-project/ {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ /kanban-test-project/index.html;
  }

  # Optional: MIME types for fonts (fix .ttf loading issues)
  # types {
  #     application/javascript js;
  #     text/css css;
  #     font/ttf ttf;
  #     font/woff woff;
  #     font/woff2 woff2;
  # }
}