server {
    listen 80;
    server_name localhost;

    location /kanban-test-project/ {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /kanban-test-project/index.html;
    }

    location /kanban-test-project/mockServiceWorker.js {
        root /usr/share/nginx/html;
        add_header Service-Worker-Allowed '/kanban-test-project/';
    }
}